# Generated by Django 4.1.3 on 2022-12-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_category_listing_comment_bid_user_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="current_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="duration",
            field=models.DateTimeField(
                blank=True, help_text="Enter the duration of the listing", null=True
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="starting_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
