# Generated by Django 4.1.3 on 2022-12-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_listing_current_price_alter_bid_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["category"]},
        ),
    ]
