# Generated by Django 4.1.3 on 2022-12-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["category_name"]},
        ),
        migrations.RenameField(
            model_name="category",
            old_name="category",
            new_name="category_name",
        ),
        migrations.AddField(
            model_name="category",
            name="category_string",
            field=models.CharField(
                blank=True,
                help_text="Enter dashed representation of the category name",
                max_length=300,
                null=True,
                unique=True,
            ),
        ),
    ]
