# Generated by Django 4.1.3 on 2022-12-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["category_string"]},
        ),
    ]
