# Generated by Django 4.1.3 on 2022-12-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_listing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="bidding_ends",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="bidding_starts",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
