# Generated by Django 4.1.3 on 2022-12-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_listing_bidding_ends_listing_bidding_starts"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="bid_count",
            field=models.IntegerField(default=0),
        ),
    ]
