# Generated by Django 4.1.3 on 2022-12-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_listing_bid_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist_item_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="watchlist", to="auctions.listing"
            ),
        ),
    ]
