# Generated by Django 4.1.3 on 2022-12-13 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_alter_user_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="bidding_ends",
        ),
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                default="default.jpg", null=True, upload_to="product_pics"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="winner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
