# Generated by Django 4.1.3 on 2022-12-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_remove_listing_bidding_ends_listing_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="imageURL",
        ),
    ]
