# Generated by Django 4.1.3 on 2022-12-15 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_alter_listing_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="listing",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_comments",
                to="auctions.listing",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="replies",
            field=models.ManyToManyField(
                blank=True, related_name="comment_replies", to="auctions.comment"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="user_watchlist", to="auctions.listing"
            ),
        ),
    ]
