# Generated by Django 4.1.3 on 2022-12-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auctions",
            "0015_comment_listing_comment_replies_alter_comment_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="duration",
            field=models.DurationField(
                blank=True, help_text="Enter the duration of the listing", null=True
            ),
        ),
    ]
