# Generated by Django 4.1.3 on 2022-12-19 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_alter_listing_duration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={"ordering": ["status", "-date_created"]},
        ),
        migrations.AlterField(
            model_name="listing",
            name="bidding_starts",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
