# Generated by Django 4.1.3 on 2022-12-19 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_alter_listing_options_alter_listing_bidding_starts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="duration",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(days=3),
                help_text="Enter the duration of the listing",
                null=True,
            ),
        ),
    ]
