# Generated by Django 4.1.3 on 2022-12-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0021_alter_listing_bidding_starts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="bidding_starts",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
