# Generated by Django 4.1.3 on 2022-12-24 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0022_alter_listing_bidding_starts"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watcher_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="listing",
            name="bidding_starts",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
