# Generated by Django 4.1.3 on 2022-12-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0023_listing_watcher_count_alter_listing_bidding_starts"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[
                    ("comment", "This is a comment"),
                    ("reply", "This is a reply"),
                ],
                default="comment",
                help_text="Comment status",
                max_length=7,
            ),
        ),
    ]
