# Generated by Django 4.1.3 on 2022-12-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0025_listing_was_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply_to",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
