# Generated by Django 4.1.3 on 2022-12-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0026_comment_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="bidding_ended",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
