# Generated by Django 4.1.3 on 2023-01-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0027_listing_bidding_ended"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="edit_count",
            field=models.IntegerField(default=0),
        ),
    ]
